# Generated by Django 4.2.5 on 2023-10-05 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="simdFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file",
                    models.FileField(upload_to="static/file/", verbose_name="文件地址"),
                ),
                (
                    "add_time",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="文件添加时间"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="joblists",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "CompanyName",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="公司名称"
                    ),
                ),
                (
                    "JobTitle",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="岗位名称"
                    ),
                ),
                (
                    "Area",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="地区"
                    ),
                ),
                (
                    "Salary",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="薪资"
                    ),
                ),
                (
                    "EducationRequirement",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="学历需求"
                    ),
                ),
                (
                    "OccupationCategory",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="职业类别"
                    ),
                ),
                (
                    "RecruitingTargets",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="招收对象"
                    ),
                ),
                (
                    "EnterpriseCategory",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="招收对象"
                    ),
                ),
                (
                    "Keywords",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="关键字"
                    ),
                ),
                (
                    "UpdateTime",
                    models.DateField(blank=True, null=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["JobTitle"], name="idx_JobTitle"),
                    models.Index(fields=["Area"], name="idx_Area"),
                    models.Index(fields=["UpdateTime"], name="idx_UpdateTime"),
                ],
            },
        ),
    ]
