# Generated by Django 4.2.5 on 2023-11-08 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aitools_Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file",
                    models.FileField(
                        upload_to="static/data/pdf_summarym/", verbose_name="文件地址"
                    ),
                ),
                (
                    "add_time",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="文件添加时间"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DayNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="日期"
                    ),
                ),
                ("count", models.IntegerField(default=0, verbose_name="网站访问次数")),
            ],
            options={
                "verbose_name": "网站日访问量统计",
                "verbose_name_plural": "网站日访问量统计",
            },
        ),
        migrations.CreateModel(
            name="Els",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
                ("els_score", models.IntegerField(default=0, verbose_name="俄罗斯方块分数")),
                (
                    "els_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="俄罗斯方块日期"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HotSearchKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Job_search_key",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword_job", models.CharField(max_length=32, verbose_name="关键字")),
                ("keyword_count", models.IntegerField(verbose_name="次数")),
            ],
        ),
        migrations.CreateModel(
            name="Snake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
                ("snake_score", models.IntegerField(default=0, verbose_name="贪吃蛇分数")),
                (
                    "snake_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="贪吃蛇日期"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=32, verbose_name="邮箱")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                ("admin", models.SmallIntegerField(default=0, verbose_name="管理员")),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
            ],
        ),
        migrations.CreateModel(
            name="UserIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=30, verbose_name="IP 地址")),
                ("ip_addr", models.CharField(max_length=30, verbose_name="IP 地理位置")),
                (
                    "end_point",
                    models.CharField(default="/", max_length=30, verbose_name="访问端点"),
                ),
                ("count", models.IntegerField(default=0, verbose_name="访问次数")),
            ],
            options={
                "verbose_name": "访问用户信息",
                "verbose_name_plural": "访问用户信息",
            },
        ),
        migrations.CreateModel(
            name="VisitNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0, verbose_name="网站访问总次数")),
            ],
            options={
                "verbose_name": "网站访问总次数",
                "verbose_name_plural": "网站访问总次数",
            },
        ),
        migrations.CreateModel(
            name="Joblists",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "CompanyName",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="公司名称"
                    ),
                ),
                (
                    "JobTitle",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="岗位名称"
                    ),
                ),
                (
                    "Area",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="地区"
                    ),
                ),
                (
                    "Salary",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="薪资"
                    ),
                ),
                (
                    "EducationRequirement",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="学历需求"
                    ),
                ),
                (
                    "OccupationCategory",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="职业类别"
                    ),
                ),
                (
                    "RecruitingTargets",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="招收对象"
                    ),
                ),
                (
                    "EnterpriseCategory",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="招收对象"
                    ),
                ),
                (
                    "Keywords",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="关键字"
                    ),
                ),
                (
                    "UpdateTime",
                    models.DateField(blank=True, null=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["JobTitle"], name="idx_JobTitle"),
                    models.Index(fields=["Area"], name="idx_Area"),
                    models.Index(fields=["UpdateTime"], name="idx_UpdateTime"),
                ],
            },
        ),
    ]
