# Generated by Django 4.1 on 2023-11-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_search_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_job', models.CharField(max_length=32, verbose_name='关键字')),
                ('keyword_count', models.IntegerField(verbose_name='次数')),
            ],
        ),
    ]
