# Generated by Django 4.2.5 on 2023-11-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_els_hotsearchkeyword_snake_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitools_files",
            name="file",
            field=models.FileField(
                upload_to="static/data/pdf_summarym/", verbose_name="文件地址"
            ),
        ),
    ]
