# Generated by Django 4.1 on 2023-11-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_els_snake_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitools_files',
            name='file',
            field=models.FileField(upload_to='static/data/pdf_summary/', verbose_name='文件地址'),
        ),
    ]
